CREATE DATABASE IF NOT EXISTS USER_INFOMATION;
USE USER_INFORMATION;
CREATE TABLE USERS (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    hashed_password TEXT NOT NULL,
    gender ENUM('MAN','WOMAN','OTHER'),
    affiliation ENUM('STUDENT','OTHER'),
    PRIMARY KEY (id)
);
