# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x12\x05image\"\"\n\x04Meta\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\"E\n\rUploadRequest\x12\x1b\n\x04meta\x18\x01 \x01(\x0b\x32\x0b.image.MetaH\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\x07\n\x05value\"#\n\x0eUploadResponse\x12\x11\n\timage_url\x18\x01 \x01(\t2F\n\x0bUploadImage\x12\x37\n\x06Upload\x12\x14.image.UploadRequest\x1a\x15.image.UploadResponse(\x01\x42\x08Z\x06/imageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006/image'
  _globals['_META']._serialized_start=22
  _globals['_META']._serialized_end=56
  _globals['_UPLOADREQUEST']._serialized_start=58
  _globals['_UPLOADREQUEST']._serialized_end=127
  _globals['_UPLOADRESPONSE']._serialized_start=129
  _globals['_UPLOADRESPONSE']._serialized_end=164
  _globals['_UPLOADIMAGE']._serialized_start=166
  _globals['_UPLOADIMAGE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
